### PR TITLE
Switch to storing page builder content in the body of the post

### PR DESCRIPTION
**Pull request by joehoyle**

### CODE REVIEW

**Comment by joehoyle** [comment]
@mattheu what do you think of this?

**Comment by lkraav** [comment]
I'm having trouble visualizing the data model just trying to read the code. What would an example post body look like after this, including any user edits?

**Comment by mattheu** [comment]
Looks OK to me - I guess the data would be JSON, and anywhere that tries to use the unfiltered post content might end up looking pretty wonky. Thats my only concern.

Plus side is of course revisions out of the box.

**Comment by joehoyle** [comment]
So the user edits are never seen ofcourse, as we dont show the post editor on the edit post page, however there this is useful and also exposed is in the post revisions, as you'll be able to restore to an earlier version of page builder content.

With this change, this means the revisions diff is just JSON which isn't ideal, however it does at least make it possible to atleast see what changed (though admittedly not that pretty).

I think we may be able to hook into the textual diff to parse the JSON first and diff it after.

**Comment by mattheu** [comment]
> I think we may be able to hook into the textual diff to parse the JSON first and diff it after.

Yeah this is possible - I've done this with meta before. Revisioning meta is possible with a plugin - https://github.com/adamsilverstein/wp-post-meta-revisions

**Comment by joehoyle** [comment]
@mattheu do you know if that plugin shows you diffs of the meta?

**Comment by mattheu** [comment]
I've definitely had that working with this plugin. For meta that stored serialized data / JSON - you could filter it to display something nicer. I'll need to check it out to refresh my memory though as this might have been a PR I was working on.

**Comment by joehoyle** [comment]
hmm yeah I'm wondering if I soudl jsut experiment with enabling that plugin and see how that gets on

**Comment by roborourke** [comment]
Why not render the HTML and save that in the post content for diffs, if the meta revisions plugin handles the actual meta diff? Would be better for quick output in non js frontend scenarios and also handle default search / excerpts and all that stuff.

Essentially what site origin page builder does.

**Comment by mattheu** [comment]
I think this would be a good idea and means you're less tied to the page builder - in future you could just disable and it would still work fine - albeit with a load of HTML in your content

**Pull request merged**
