### PR TITLE
Refresh WYSIWYG after sort

### PR DESCRIPTION
**Pull request by mattheu**
Bit of a rabbit hole this one...

The problem is, after we drag a WYSIWYG module, the TinyMCE editor breaks and is unusable. The solution is to detect the sort stop event and re-initialize. 

The tricky part is that the event needs to somehow be passed from the builder view right down to the field view. And right now - there is no connection between the elements on the page and the sub-views. Some kind of record of child views perhaps?

Now WP has its own version of backbone.View (which really... we should have used all along) and this handles subviews. This means we keep a reference of child views and can more easily pass the event on to the field.

So thats what I did - but it wasn't so easy as the switch to wp.Backbone.view meant rewriting the templates to use the wp-core template syntax and tweaking the way we call render.

Downside. This is probably a breaking backwards compatibility change for anyone who has completely CUSTOM module edit backbone views, or has added custom field views. Standard module registration will be unaffected.

Worth the change? I think so. I'm keen to push dev forwards and I don't think its widely used!

### CODE REVIEW

**Comment by mattheu** [comment]
@roborourke Could you do me a review on this one? Are you using any custom field views at all? Thats the only blocker I could see to this, but I don't think its something people are doing.

**Comment by roborourke** [comment]
@mattheu I'll test it out. I've not set up any custom views yet but could try it out to see.

**Comment by mattheu** [comment]
I wouldn't worry about the custom views... this will be a breaking change but only for people who have really hacked about with it.

**Comment by mattheu** [comment]
Thanks @roborourke

**Pull request merged**
